import dayjs from 'dayjs';
import ScheduleIcon from "@mui/icons-material/Schedule";
import FactoryIcon from "@mui/icons-material/Factory";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import CancelIcon from "@mui/icons-material/Close";
import ContentCut from "@mui/icons-material/ContentCut"

export const dummyProducts = [
    {
        _id: 'prod1',
        name: 'Classic Leather Tote',
        category: 'Bags',
        variants: [
            { _id: 'var1', name: 'Brown, Large' },
            { _id: 'var2', name: 'Black, Medium' },
            { _id: 'var3', name: 'Tan, Small' },
        ],
    },
    {
        _id: 'prod2',
        name: 'Executive Briefcase',
        category: 'Bags',
        variants: [
            { _id: 'var4', name: 'Black' },
            { _id: 'var5', name: 'Brown' },
        ],
    },
    {
        _id: 'prod3',
        name: 'Travel Backpack',
        category: 'Bags',
        variants: [
            { _id: 'var6', name: 'Navy Blue' },
            { _id: 'var7', name: 'Forest Green' },
            { _id: 'var8', name: 'Charcoal' },
        ],
    },
    {
        _id: 'prod4',
        name: 'Crossbody Messenger',
        category: 'Bags',
        variants: [
            { _id: 'var9', name: 'Cognac' },
            { _id: 'var10', name: 'Black' },
        ],
    },
    {
        _id: 'prod5',
        name: 'Leather Wallet',
        category: 'Accessories',
        variants: [
            { _id: 'var11', name: 'Brown, Bi-fold' },
            { _id: 'var12', name: 'Black, Tri-fold' },
        ],
    },
];

export const dummyMaterials = [
    {
        _id: 'mat1',
        name: 'Premium Cowhide Leather',
        variants: [
            { _id: 'mvar1', name: 'Brown', stock: 150, unit: 'sq ft' },
            { _id: 'mvar2', name: 'Black', stock: 200, unit: 'sq ft' },
            { _id: 'mvar3', name: 'Tan', stock: 80, unit: 'sq ft' },
        ],
        cost: 12.5,
    },
    {
        _id: 'mat2',
        name: 'Nylon Lining',
        variants: [
            { _id: 'mvar4', name: 'Black', stock: 500, unit: 'meters' },
            { _id: 'mvar5', name: 'Brown', stock: 300, unit: 'meters' },
        ],
        cost: 3.2,
    },
    {
        _id: 'mat3',
        name: 'YKK Zipper',
        variants: [
            { _id: 'mvar6', name: 'Gold, 12 inch', stock: 1000, unit: 'pieces' },
            { _id: 'mvar7', name: 'Silver, 12 inch', stock: 800, unit: 'pieces' },
        ],
        cost: 2.5,
    },
    {
        _id: 'mat4',
        name: 'Metal Buckle',
        variants: [
            { _id: 'mvar8', name: 'Antique Brass', stock: 500, unit: 'pieces' },
            { _id: 'mvar9', name: 'Nickel', stock: 400, unit: 'pieces' },
        ],
        cost: 4.0,
    },
    {
        _id: 'mat5',
        name: 'Waxed Thread',
        variants: [
            { _id: 'mvar10', name: 'Brown', stock: 100, unit: 'spools' },
            { _id: 'mvar11', name: 'Black', stock: 120, unit: 'spools' },
        ],
        cost: 8.0,
    },
];

export const dummyUsers = [
    { _id: 'user1', firstName: 'John', lastName: 'Smith', role: 'Production Manager' },
    { _id: 'user2', firstName: 'Maria', lastName: 'Garcia', role: 'Cutting Specialist' },
    { _id: 'user3', firstName: 'Ahmed', lastName: 'Hassan', role: 'Cutting Specialist' },
    { _id: 'user4', firstName: 'Lisa', lastName: 'Chen', role: 'Quality Control' },
    { _id: 'user5', firstName: 'Mike', lastName: 'Johnson', role: 'Supervisor' },
];

export const productionGroups = ['Group A', 'Group B', 'Group C', 'Group D'];

export const dummyCutOrders = [
    {
        _id: 'co1',
        productId: 'prod1',
        productName: 'Classic Leather Tote',
        category: 'Bags',
        variantId: 'var1',
        variantName: 'Brown, Large',
        quantity: 50,
        relatedOrderId: null,
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar1',
                variantName: 'Brown',
                quantityNeeded: 125,
                listsNeeded: 5,
                reserved: true,
            },
            {
                materialId: 'mat2',
                materialName: 'Nylon Lining',
                variantId: 'mvar5',
                variantName: 'Brown',
                quantityNeeded: 75,
                listsNeeded: 3,
                reserved: true,
            },
            {
                materialId: 'mat3',
                materialName: 'YKK Zipper',
                variantId: 'mvar6',
                variantName: 'Gold, 12 inch',
                quantityNeeded: 100,
                listsNeeded: null,
                reserved: false,
            },
        ],
        materialsUsed: [],
        estimatedMaterialCost: 2187.5,
        actualMaterialCost: 0,
        createdBy: { userId: 'user1', firstName: 'John', lastName: 'Smith' },
        assignedToCutting: {
            userId: 'user2',
            firstName: 'Maria',
            lastName: 'Garcia',
            assignedDate: dayjs('2024-01-15').toDate(),
        },
        assignedToProduction: null,
        status: 'CUTTING',
        priority: 'HIGH',
        addedDate: dayjs('2024-01-14').toDate(),
        dueDate: dayjs('2024-01-25').toDate(),
        cuttingStartedDate: dayjs('2024-01-16').toDate(),
        cuttingCompletedDate: null,
        productionStartedDate: null,
        completedDate: null,
        instructions: 'Use pattern v2.3 for this batch. Extra attention to stitching lines.',
        notes: 'Customer prefers slightly darker shade of brown.',
        issues: [],
    },
    {
        _id: 'co2',
        productId: 'prod2',
        productName: 'Executive Briefcase',
        category: 'Bags',
        variantId: 'var4',
        variantName: 'Black',
        quantity: 25,
        relatedOrderId: 'order123',
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar2',
                variantName: 'Black',
                quantityNeeded: 87.5,
                listsNeeded: 4,
                reserved: true,
            },
            {
                materialId: 'mat4',
                materialName: 'Metal Buckle',
                variantId: 'mvar9',
                variantName: 'Nickel',
                quantityNeeded: 50,
                listsNeeded: null,
                reserved: true,
            },
        ],
        materialsUsed: [
            { materialId: 'mat1', variantId: 'mvar2', quantityUsed: 90, listsUsed: 4, wastage: 2.5 },
            { materialId: 'mat4', variantId: 'mvar9', quantityUsed: 50, listsUsed: null, wastage: 0 },
        ],
        estimatedMaterialCost: 1293.75,
        actualMaterialCost: 1325.0,
        createdBy: { userId: 'user5', firstName: 'Mike', lastName: 'Johnson' },
        assignedToCutting: {
            userId: 'user3',
            firstName: 'Ahmed',
            lastName: 'Hassan',
            assignedDate: dayjs('2024-01-10').toDate(),
        },
        assignedToProduction: { group: 'Group A', assignedDate: dayjs('2024-01-14').toDate() },
        status: 'IN_PRODUCTION',
        priority: 'URGENT',
        addedDate: dayjs('2024-01-08').toDate(),
        dueDate: dayjs('2024-01-20').toDate(),
        cuttingStartedDate: dayjs('2024-01-11').toDate(),
        cuttingCompletedDate: dayjs('2024-01-13').toDate(),
        productionStartedDate: dayjs('2024-01-14').toDate(),
        completedDate: null,
        instructions: 'Premium stitching required. Double check all buckle placements.',
        notes: 'VIP customer order - highest quality standards.',
        issues: [
            {
                description: 'Minor color inconsistency in one leather batch',
                reportedBy: { userId: 'user4', name: 'Lisa Chen' },
                reportedDate: dayjs('2024-01-12').toDate(),
                resolved: true,
            },
        ],
    },
    {
        _id: 'co3',
        productId: 'prod3',
        productName: 'Travel Backpack',
        category: 'Bags',
        variantId: 'var6',
        variantName: 'Navy Blue',
        quantity: 100,
        relatedOrderId: null,
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar2',
                variantName: 'Black',
                quantityNeeded: 200,
                listsNeeded: 8,
                reserved: false,
            },
            {
                materialId: 'mat2',
                materialName: 'Nylon Lining',
                variantId: 'mvar4',
                variantName: 'Black',
                quantityNeeded: 150,
                listsNeeded: 6,
                reserved: false,
            },
            {
                materialId: 'mat3',
                materialName: 'YKK Zipper',
                variantId: 'mvar7',
                variantName: 'Silver, 12 inch',
                quantityNeeded: 300,
                listsNeeded: null,
                reserved: false,
            },
        ],
        materialsUsed: [],
        estimatedMaterialCost: 3730.0,
        actualMaterialCost: 0,
        createdBy: { userId: 'user1', firstName: 'John', lastName: 'Smith' },
        assignedToCutting: null,
        assignedToProduction: null,
        status: 'PENDING',
        priority: 'NORMAL',
        addedDate: dayjs('2024-01-18').toDate(),
        dueDate: dayjs('2024-02-15').toDate(),
        cuttingStartedDate: null,
        cuttingCompletedDate: null,
        productionStartedDate: null,
        completedDate: null,
        instructions: 'Standard production process.',
        notes: 'Stock replenishment order.',
        issues: [],
    },
    {
        _id: 'co4',
        productId: 'prod4',
        productName: 'Crossbody Messenger',
        category: 'Bags',
        variantId: 'var9',
        variantName: 'Cognac',
        quantity: 35,
        relatedOrderId: 'order456',
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar3',
                variantName: 'Tan',
                quantityNeeded: 52.5,
                listsNeeded: 3,
                reserved: true,
            },
            {
                materialId: 'mat5',
                materialName: 'Waxed Thread',
                variantId: 'mvar10',
                variantName: 'Brown',
                quantityNeeded: 2,
                listsNeeded: null,
                reserved: true,
            },
        ],
        materialsUsed: [
            { materialId: 'mat1', variantId: 'mvar3', quantityUsed: 54, listsUsed: 3, wastage: 1.5 },
            { materialId: 'mat5', variantId: 'mvar10', quantityUsed: 2, listsUsed: null, wastage: 0 },
        ],
        estimatedMaterialCost: 672.25,
        actualMaterialCost: 691.0,
        createdBy: { userId: 'user5', firstName: 'Mike', lastName: 'Johnson' },
        assignedToCutting: {
            userId: 'user2',
            firstName: 'Maria',
            lastName: 'Garcia',
            assignedDate: dayjs('2024-01-05').toDate(),
        },
        assignedToProduction: { group: 'Group B', assignedDate: dayjs('2024-01-09').toDate() },
        status: 'COMPLETED',
        priority: 'NORMAL',
        addedDate: dayjs('2024-01-03').toDate(),
        dueDate: dayjs('2024-01-15').toDate(),
        cuttingStartedDate: dayjs('2024-01-06').toDate(),
        cuttingCompletedDate: dayjs('2024-01-08').toDate(),
        productionStartedDate: dayjs('2024-01-09').toDate(),
        completedDate: dayjs('2024-01-14').toDate(),
        instructions: null,
        notes: null,
        issues: [],
    },
    {
        _id: 'co5',
        productId: 'prod5',
        productName: 'Leather Wallet',
        category: 'Accessories',
        variantId: 'var11',
        variantName: 'Brown, Bi-fold',
        quantity: 200,
        relatedOrderId: null,
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar1',
                variantName: 'Brown',
                quantityNeeded: 100,
                listsNeeded: 4,
                reserved: true,
            },
            {
                materialId: 'mat5',
                materialName: 'Waxed Thread',
                variantId: 'mvar10',
                variantName: 'Brown',
                quantityNeeded: 4,
                listsNeeded: null,
                reserved: true,
            },
        ],
        materialsUsed: [],
        estimatedMaterialCost: 1282.0,
        actualMaterialCost: 0,
        createdBy: { userId: 'user1', firstName: 'John', lastName: 'Smith' },
        assignedToCutting: {
            userId: 'user3',
            firstName: 'Ahmed',
            lastName: 'Hassan',
            assignedDate: dayjs('2024-01-17').toDate(),
        },
        assignedToProduction: null,
        status: 'CUTTING',
        priority: 'LOW',
        addedDate: dayjs('2024-01-16').toDate(),
        dueDate: dayjs('2024-02-10').toDate(),
        cuttingStartedDate: dayjs('2024-01-18').toDate(),
        cuttingCompletedDate: null,
        productionStartedDate: null,
        completedDate: null,
        instructions: 'Use smaller cutting templates for wallets.',
        notes: 'Large batch for retail inventory.',
        issues: [
            {
                description: 'Thread spool running low',
                reportedBy: { userId: 'user3', name: 'Ahmed Hassan' },
                reportedDate: dayjs('2024-01-19').toDate(),
                resolved: false,
            },
        ],
    },
    {
        _id: 'co6',
        productId: 'prod1',
        productName: 'Classic Leather Tote',
        category: 'Bags',
        variantId: 'var2',
        variantName: 'Black, Medium',
        quantity: 30,
        relatedOrderId: 'order789',
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar2',
                variantName: 'Black',
                quantityNeeded: 60,
                listsNeeded: 3,
                reserved: false,
            },
            {
                materialId: 'mat2',
                materialName: 'Nylon Lining',
                variantId: 'mvar4',
                variantName: 'Black',
                quantityNeeded: 45,
                listsNeeded: 2,
                reserved: false,
            },
        ],
        materialsUsed: [],
        estimatedMaterialCost: 894.0,
        actualMaterialCost: 0,
        createdBy: { userId: 'user5', firstName: 'Mike', lastName: 'Johnson' },
        assignedToCutting: null,
        assignedToProduction: null,
        status: 'PENDING',
        priority: 'HIGH',
        addedDate: dayjs('2024-01-19').toDate(),
        dueDate: dayjs('2024-01-22').toDate(),
        cuttingStartedDate: null,
        cuttingCompletedDate: null,
        productionStartedDate: null,
        completedDate: null,
        instructions: 'Rush order - prioritize this batch.',
        notes: 'Customer needs by end of week.',
        issues: [],
    },
    {
        _id: 'co7',
        productId: 'prod2',
        productName: 'Executive Briefcase',
        category: 'Bags',
        variantId: 'var5',
        variantName: 'Brown',
        quantity: 15,
        relatedOrderId: null,
        materialsRequired: [
            {
                materialId: 'mat1',
                materialName: 'Premium Cowhide Leather',
                variantId: 'mvar1',
                variantName: 'Brown',
                quantityNeeded: 52.5,
                listsNeeded: 3,
                reserved: true,
            },
            {
                materialId: 'mat4',
                materialName: 'Metal Buckle',
                variantId: 'mvar8',
                variantName: 'Antique Brass',
                quantityNeeded: 30,
                listsNeeded: null,
                reserved: true,
            },
        ],
        materialsUsed: [],
        estimatedMaterialCost: 776.25,
        actualMaterialCost: 0,
        createdBy: { userId: 'user1', firstName: 'John', lastName: 'Smith' },
        assignedToCutting: null,
        assignedToProduction: null,
        status: 'CANCELLED',
        priority: 'NORMAL',
        addedDate: dayjs('2024-01-10').toDate(),
        dueDate: dayjs('2024-01-30').toDate(),
        cuttingStartedDate: null,
        cuttingCompletedDate: null,
        productionStartedDate: null,
        completedDate: null,
        instructions: null,
        notes: 'Cancelled due to material shortage.',
        issues: [],
    },
];


export const STATUS_CONFIG = {
    PENDING: { color: 'warning', icon: <ScheduleIcon />, label: 'Pending' },
    CUTTING: { color: 'info', icon: <ContentCut />, label: 'Cutting' },
    IN_PRODUCTION: { color: 'info', icon: <FactoryIcon />, label: 'In Production' },
    COMPLETED: { color: 'success', icon: <CheckCircleIcon />, label: 'Completed' },
    CANCELLED: { color: 'error', icon: <CancelIcon />, label: 'Cancelled' },
};

export const PRIORITY_CONFIG = {
    LOW: { color: 'info', label: 'Low' },
    NORMAL: { color: 'info', label: 'Normal' },
    HIGH: { color: 'warning', label: 'High' },
    URGENT: { color: 'error', label: 'Urgent' },
};

export const STATUS_STEPS = ['PENDING', 'CUTTING', 'IN_PRODUCTION', 'COMPLETED'];
